version: "3.9"

services:
  master:
    container_name: master
    hostname: master
    build:
      context: ./master
    environment:
      OPENSEARCH_URL: "http://coordinating"
  opensearch01:
    image: opensearchproject/opensearch:1.3.0
    container_name: opensearch01
    environment:
      - node.name=opensearch01
    env_file:
      - ./opensearch/default.env
    volumes:
      - ${PWD}/opensearch/files/opensearch.yaml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  opensearch02:
    image: opensearchproject/opensearch:1.3.0
    container_name: opensearch02
    environment:
      - node.name=opensearch02
    env_file:
      - ./opensearch/default.env
    volumes:
      - ${PWD}/opensearch/files/opensearch.yaml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch01:9200","http://opensearch02:9200"]'
    env_file:
      - ./opensearch-dashboards/default.env
    volumes:
      - ${PWD}/opensearch-dashboards/files/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml