all:
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_user: "ansible"
    ansible_become: true
    ansible_method: sudo
    ansible_become_flags: "-H -S -n -i"
    ansible_become_user: "root"
    ansible_python_interpreter: python3
  children:
    foo-application:
      children:
        foo-web:
          hosts:
            foo-web0:
            foo-web1:
        foo-app:
          hosts:
            foo-app0:
            foo-app1:
        foo-db:
          hosts:
            foo-db0:
            foo-db1: