---
- name: "Ensure '/var/www/html' Directory"
  file:
    path: /var/www/html
    state: directory
    recurse: true
    owner: root
    group: root
    mode: 0755
  tags: [ frontend ]

#- name: "Install 'Apache2' Package"
#  apt:
#    name: apache2
#    state: present
#    update_cache: yes
#  tags: [ frontend ]

- name: "Prepare 'index.html' Template File"
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  tags: [ frontend ]

#- name: "Ensure 'Apache2' Service is Running"
#  shell:
#    cmd: apache2ctl start
#  tags: [ frontend ]