---
- hosts: prod-opensearch
  gather_facts: false
  roles:
    - role: remote-cluster
      tags:
        - remote-cluster

- hosts: ppe-opensearch
  gather_facts: false
  roles:
    - role: remote-cluster
      tags:
        - remote-cluster

- hosts: qat-opensearch
  gather_facts: false
  roles:
    - role: remote-cluster
      tags:
        - remote-cluster