---
- hosts: opensearch
  gather_facts: false

  tasks:
    - include_role:
        name: ansible-run-time
      vars:
        task: "All"
        status: "Started"
    - include_role:
        name: indices
    - include_role:
        name: unassigned-timeout
    - include_role:
        name: indice-recovery
    - include_role:
        name: remote-cluster
    - include_role:
        name: ansible-run-time
      vars:
        task: "All"
        status: "Finished"