cluster:
  protocol: http
  host: ppe-opensearch
  port: 9200

remote_clusters:
  - name: prod-opensearch
    seeds:
      - name: ppe-opensearch
        port: 9300
  - name: qat-opensearch
    seeds:
      - name: qat-opensearch
        port: 9300