cluster:
  protocol: http
  host: qat-opensearch
  port: 9200

remote_clusters:
  - name: prod-opensearch
    seeds:
      - name: prod-opensearch
        port: 9300
  - name: ppe-opensearch
    seeds:
      - name: prod-opensearch
        port: 9300