cluster:
  protocol: http
  host: qat-opensearch
  port: 9200

cluster_url: "{{ cluster.protocol }}://{{ cluster.host }}:{{ cluster.port }}"

remote_clusters:
  - name: prod-opensearch
    seeds:
      - name: prod-opensearch
        port: 9300
  - name: ppe-opensearch
    seeds:
      - name: ppe-opensearch
        port: 9300

index:
  unassigned:
    node_left:
      delayed_timeout: 10m